---
irc:
  uri: "irc:iBridge@irc.nlnog.net:6668?nickname=iBridge&channels=#testing123,#testing666&realname=Just a test"

telegram:
  uri: "telegram:bots/numbers:numberAndLetters?delay=5s"

publish:
  url: "https://example.com/telegram-photos"

local:
  file-path: "/var/www/htdocs/example.com/telegram-photos"

channel-group-mappings:
  channels:
    'mychan1': '-111111111' # Without a starting hash (#)
    'mychan2': '-222222222'
    'mychan3': '-333333333'

